version: "3.8"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=basic_bank
      - PGUSER=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/basic_bank?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy